# Add trigger
name: Build and Deploy Script
on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ Enables manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install NodeJS
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1

      # Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.1
      - run: pnpm install --no-frozen-lockfile
        working-directory: 202401EffectiveAngular/business-tools-monorepo/

      # Build Angular App with correct base href
      - name: Build Angular App
        run: pnpm nx build expenses-registration --no-cloud --base-href /Angular-Study-starters/
        working-directory: 202401EffectiveAngular/business-tools-monorepo/

      # Setup Git on the VM
      - name: Set up Git
        run: |
          git config --global user.email "fengyanglddin09@gmail.com"
          git config --global user.name "Mark Lin"

      # Deploy the Angular App to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/apps/finance/expenses-registration
        working-directory: 202401EffectiveAngular/business-tools-monorepo/
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_PAGES }}
